apiVersion: v1alpha
kind: imagerunner
sauce:
region: us-west-1
suites:
  - name: Hosted Test Orchestration Demo
    workload: webdriver
    image: $DOCKER_IMAGE
    imagePullAuth:
      user: $DOCKER_USERNAME
      token: $DOCKER_PASSWORD
    entrypoint: "pytest -n 15"
